### ISSUE TITLE
Cookies.

### ISSUE THREAD

**Issue by egobrain** [sockjs/sockjs-erlang#16]
Need help.
Is there way to get cookies from request.
I'm using cowboy and want to authorize user before connect him.
Is there any way to solve my problem ?

**Comment by majek** [comment]
@Egobrain  Due to the nature of SockJS (especially the iframe-based transports), Cookie and Origin headers may be very misleading. Using them for authorization will inevitably lead to security issues. Further reading:
- https://github.com/sockjs/sockjs-node/commit/1241bde38fafc21afcc6d0f2c310aa5348aaf1a0
- https://github.com/sockjs/sockjs-node/pull/49
- https://github.com/sockjs/sockjs-node/issues/50
- https://github.com/sockjs/sockjs-node/pull/29
- https://en.wikipedia.org/wiki/Cross-site_request_forgery

Please consider sending a unique authorization token over SockJS.

Why do you need to authorize before the connection is established?

**Comment by egobrain** [comment]
I'm developing app where only authorized users can access server.
I don want to handle unauthorized connection.

 Marek Majkowski  
reply@reply.github.com  
:

**Comment by majek** [comment]
Okay, that's what I do:
- await for connection from anyone
- on the server side receive authorisation token as first thing on the connection
- if token is invalid or if it doesn't appear in let's say 5 seconds, abruptly close the connection

Will that work for you?

**Comment by egobrain** [comment]
Yes. I can do so... Thank you.
